server:
  port: 12100

xxl:
  job:
    enabled: true
    admin:
      addresses: localhost:3000
    executor:
      host: localhost
      port: 12100
      app-name: kjb-exe









































